#!/bin/bash -x
if ! ssh-add -l > /dev/null 2>&1; then
    for agent in /tmp/ssh-*/agent.*; do
        [ -O $agent ] || continue
        export SSH_AUTH_SOCK=$agent
        if ssh-add -l > /dev/null 2>&1; then
            export SSH_AUTH_SOCK=$agent
        fi
    done
fi

